# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DreamDesign' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DreamDesign

  target 'DreamDesignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DreamDesignUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 4.0.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'Toast', '~> 3.1.0'
end
